<?php

/**
 * Implementation of hook_block().
 */
function drupalcampaustin_library_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['dca_header_links'] = array(
      'info' => t('DCA: Header links'),
    );
    $blocks['dca_header_ribbon'] = array(
      'info' => t('DCA: Header ribbon'),
    );
    $blocks['dca_user_stats'] = array(
      'info' => t('DCA: User stats'),
    );
    return $blocks;
  }
  else if ($op == 'view') {
    global $user;
    $user_loaded = user_load($user->uid);

    switch($delta) {
      case 'dca_header_links':
        $block = array(
          'subject' => '',
          'content' => drupalcampaustin_library_block_header_links($user_loaded),
        );
        break;
      case 'dca_header_ribbon':
        $block = array(
          'subject' => '',
          'content' => drupalcampaustin_library_block_header_ribbon($user_loaded),
        );
        break;
      case 'dca_user_stats':
        $block = array(
          'subject' => 'User stats',
          'content' => drupalcampaustin_library_block_user_stats($user_loaded),
        );
        break;
    }
    return $block;
  }
}

function drupalcampaustin_library_block_header_links($user) {
  $links = array();

  // Is the user logged in?
  if ($user->uid != 0) {
    $links[] = l(t('My account'), 'user/' . $user->uid);

    // Has the user created a profile page?
    if ($user->has_profile) {
      // See drupal_get_destination() if we want to add a destination query
      // http://api.drupal.org/api/function/drupal_get_destination/6
      $links[] = l(t('My profile page'), 'node/' . $user->profile->nid);
    }
    else {
      $links[] = l(t('Create my profile page'), 'node/add/profile');
    }

    if (!$user->has_registered) {
      // Add a "cart" link if the user is mid-checkout
      $cart = uc_cart_get_contents();
      if (!empty($cart)) {
        $links[] = l(t('My cart'), 'cart');
      }
    }

    $links[] = l(t('Log out'), 'logout');
  }
  else {
    $links[] = l(t('Log in'), 'user/login');
    $links[] = l(t('Register'), 'user/register');
  }

  $output = '';
  $output .= '<div id="header-links">';
  $output .= '<div id="header-links-right"></div>';
  $output .= '<div id="header-links-text">';
  $output .= implode(' <span>|</span> ', $links);
  $output .= '</div>';
  $output .= '<div id="header-links-left"></div>';
  $output .= '</div>';

  return $output;
}

function drupalcampaustin_library_block_header_ribbon($user) {
  $path = '/' . drupal_get_path('theme', 'drupalcampaustin') . '/images/';

  $output = '';
  $output .= '<div id="header-ribbon">';

  // Is the user logged in?
  if ($user->uid != 0) {

    // Has the user finished everything?
    if ($user->has_profile && $user->has_registered) {
      $output .= '<img src="' . $path . 'header-ribbon-done.png" class="steps" alt="' . t("You're done!") . '" />';
    }
    else {
      $output .= '<img src="' . $path . 'header-ribbon-step1-done.png" class="steps" alt="' . t('Create account: Done!') . '" />';

      // Has the user created a profile page?
      if ($user->has_profile) {
        $output .= '<img src="' . $path . 'header-ribbon-step2-done.png" class="steps" alt="' . t('Create profile: Done!') . '" />';
      }
      else {
        $output .= l('<img src="' . $path . 'header-ribbon-step2.png" class="steps" alt="' . t('Create profile') . '" />', 'node/add/profile', array('html' => TRUE, 'attributes' => array('title' => t('Create profile'))));
      }

      // Has the user registered?
      if ($user->has_registered) {
        $output .= '<img src="' . $path . 'header-ribbon-step3-done.png" alt="' . t('Registration: Done!') . '" />';
      }
      else {
        $output .= l('<img src="' . $path . 'header-ribbon-step3.png" alt="' . t('Register') . '" />', 'node/2', array('html' => TRUE, 'attributes' => array('title' => t('Register'))));
        
        // Add a persistent message reminding users to register
        // node/2 == Product page
        // cart == Any shopping cart page
        $path = $_GET['q'];
        if (($path != 'node/add/profile') && ($path != 'node/2') && (arg(0) != 'cart')) {
          drupal_set_message(t('<strong>Don\'t forget to !register!</strong>', array('!register' => l(t('register to attend DrupalCamp Austin 2009'), 'node/2'), )));
        }
      }
    }
  }
  else {
    $output .= l('<img src="' . $path . 'header-ribbon-register.png" class="steps" alt="' . t('Register') . '" />', 'user/register', array('html' => TRUE, 'attributes' => array('title' => t('Register'))));
  }

  $output .= '</div>';

  return $output;
}

function drupalcampaustin_library_block_user_stats($user) {
  $display_views = array(
    'internal_users_registered',
    'internal_users_registered_free',
    'internal_users_unregistered',
    'internal_users_vegetarian',
    'internal_users_vegan',
  );

  $output = array();

  foreach ($display_views as $display_view) {
    $view = views_get_view($display_view);
    if (!empty($view)) {
      // Execute view query
      // Results will be stored as an array in $view->result
      $view->execute_display('default');
      $output[] = $view->display['default']->display_options['title'] . ': ' . count($view->result);
    }
  }

  return implode('<br />', $output);
}

/**
 * Implementation of hook_user().
 */
function drupalcampaustin_library_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      $account->profile = drupalcampaustin_library_user_profile($account->uid);

      // Has the user created a profile page?
      if (!empty($account->profile)) {
        $account->has_profile = TRUE;
      }
      else {
        $account->has_profile = FALSE;
      }

      // Has the user registered?
      if (drupalcampaustin_library_user_has_role('attendee', $account)) {
        $account->has_registered = TRUE;
      }
      else {
        $account->has_registered = FALSE;
      }
      break;

    case 'view':
      global $user;
      $account->content['summary']['#title'] = t('Account summary');
      $account->content['summary']['#weight'] = -10;
      $account->content['summary']['user_profile'] = array(
        '#type' => 'user_profile_item',
        '#title' => t('Profile page'),
        '#value' => drupalcampaustin_library_user_account_page($account, $user),
      );
      break;
  }
}

function drupalcampaustin_library_user_profile($uid) {
  $profile = content_profile_load('profile', $uid);
  if ($profile != FALSE) {
    return $profile;
  }
  return NULL;
}

function drupalcampaustin_library_user_account_page($user, $current_user) {
  $output = '';

  // Is the user viewing his/her own account page?
  if ($user->uid == $current_user->uid) {
    if ($user->has_profile) {
      $output = l(t('View my profile page'), 'node/' . $user->profile->nid);
      $output .= '<br />';
      $output .= l(t('Edit my profile page'), 'node/' . $user->profile->nid . '/edit');
    }
    else {
      $output = l(t('Create my profile page'), 'node/add/profile');
    }
  }
  elseif ($user->has_profile) {
    $output = l(t('Go to this user\'s profile page'), 'node/' . $user->profile->nid);
  }
  else {
    $output = t('This user has not created a profile page');
  }

  return $output;
}

/**
 * Check to see if a user has been assigned a certain role.
 *
 * @param $role
 *   The name of the role you're trying to find.
 * @param $user
 *   The user object for the user you're checking; defaults to the current user.
 * @return
 *   TRUE if the user object has the role, FALSE if it does not.
 */
function drupalcampaustin_library_user_has_role($role, $user = NULL) {
  if ($user == NULL) {
    global $user;
  }
  if (is_array($user->roles) && in_array($role, array_values($user->roles))) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_form_alter().
 */
function drupalcampaustin_library_form_alter(&$form, $form_state, $form_id) {
//  print $form_id;
}

function drupalcampaustin_library_form_comment_form_alter(&$form, &$form_state) {
  unset($form['_author']);
  unset($form['comment_filter']['comment']['#title']);
  unset($form['preview']);
}

function drupalcampaustin_library_form_contact_mail_user_alter(&$form, &$form_state) {
  $profile = drupalcampaustin_library_user_profile(arg(1));
  if (!empty($profile)) {
    $form['#redirect'] = 'node/' . $profile->nid;
  }
  else {
    $form['#redirect'] = '<front>';
  }
}

function drupalcampaustin_library_form_uc_cart_view_form_alter(&$form, &$form_state) {
  unset($form['update']);
  unset($form['items'][0]['remove']);
  unset($form['items'][0]['image']);
  unset($form['items']['#columns']['remove']);
  unset($form['items']['#columns']['image']);

  $form['items']['#columns']['desc']['cell'] = 'Description';
}

function drupalcampaustin_library_form_profile_node_form_alter(&$form, &$form_state) {
  // Hide the extraneous title ("Name") field
  $form['title']['#type'] = 'hidden';
  // Add placeholder for #value
  $form['title']['#value'] = NULL;
  // Add a validation function that will fill in the value of the title ("Name") field
  $form['#validate'][] = 'drupalcampaustin_library_profile_node_form_validate';

  $form['revision_information']['#type'] = 'hidden';
}

function drupalcampaustin_library_profile_node_form_validate($form, &$form_state) {
  $name = $form_state['values']['field_profile_firstname'][0]['value'] . ' ' . $form_state['values']['field_profile_lastname'][0]['value'];
  form_set_value($form['title'], $name, $form_state);
}

function drupalcampaustin_library_advforum_styles() {
  $items = array();
  $items['drupalcampaustin'] = array(
    'directory' => '../../themes/drupalcampaustin/forum',
  );
  return $items;
}
