<?php

/**
 * Implementation of hook_block().
 */
function drupalcampaustin_library_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks['dca_header_links'] = array(
      'info' => t('DCA: Header links'),
    );
    $blocks['dca_header_ribbon'] = array(
      'info' => t('DCA: Header ribbon'),
    );
    return $blocks;
  }
  else if ($op == 'view') {
    global $user;
    $user_loaded = user_load($user->uid);

    switch($delta) {
      case 'dca_header_links':
        $block = array(
          'subject' => '',
          'content' => drupalcampaustin_library_block_header_links($user_loaded),
        );
        break;
      case 'dca_header_ribbon':
        $block = array(
          'subject' => '',
          'content' => drupalcampaustin_library_block_header_ribbon($user_loaded),
        );
        break;
    }
    return $block;
  }
}

function drupalcampaustin_library_block_header_links($user) {
  $links = array();

  // Is the user logged in?
  if ($user->uid != 0) {
    $links[] = l(t('My account'), 'user/' . $user->uid);

    // Has the user created a profile page?
    if ($user->profile_page) {
      // See drupal_get_destination() if we want to add a destination query
      // http://api.drupal.org/api/function/drupal_get_destination/6
      $links[] = l(t('My profile page'), 'node/' . $user->profile_page);
    }
    else {
      $links[] = l(t('Create my profile page'), 'node/add/profile');
    }

    // Add a "cart" link if the user is mid-checkout
    $cart = uc_cart_get_contents();
    if (!empty($cart)) {
      $links[] = l(t('My cart'), 'cart');
    }

    $links[] = l(t('Log out'), 'logout');
  }
  else {
    $links[] = l(t('Log in'), 'user/login');
    $links[] = l(t('Create an account'), 'user/register');
  }

  $output = '';
  $output .= '<div id="header-links">';
  $output .= '<div id="header-links-right"></div>';
  $output .= '<div id="header-links-text">';
  $output .= implode(' <span>|</span> ', $links);
  $output .= '</div>';
  $output .= '<div id="header-links-left"></div>';
  $output .= '</div>';

  return $output;
}

function drupalcampaustin_library_block_header_ribbon($user) {
  $path = '/' . drupal_get_path('theme', 'drupalcampaustin') . '/images/';

  $output = '';
  $output .= '<div id="header-ribbon">';

  // Is the user logged in?
  if ($user->uid != 0) {

    // See all to FALSE
    $profile_exists = FALSE;
    $registered = FALSE;
    // Has the user created a profile page?
    if ($user->profile_page) {
      $profile_exists = TRUE;
    }
    // Has the user registered?
    if (drupalcampaustin_library_user_has_role('attendee', $user)) {
      $registered = TRUE;
    }

    // Has the user finished everything?
    if ($profile_exists && $registered) {
      $output .= '<img src="' . $path . 'header-ribbon-done.png" class="steps" alt="You\'re done!" />';
    }
    else {
      $output .= '<img src="' . $path . 'header-ribbon-step1-done.png" class="steps" alt="Create account: Done!" />';

      // Has the user created a profile page?
      if ($profile_exists) {
        $output .= '<img src="' . $path . 'header-ribbon-step2-done.png" class="steps" alt="Create profile: Done!" />';
      }
      else {
        $output .= '<a href="/node/add/profile" title="Create profile"><img src="' . $path . 'header-ribbon-step2.png" class="steps" alt="Create profile" /></a>';
      }

      // Has the user registered?
      if ($registered) {
        $output .= '<img src="' . $path . 'header-ribbon-step3-done.png" alt="Registration: Done!" />';
      }
      else {
        $output .= '<a href="/products/drupalcamp-austin-2009-registration" title="Register"><img src="' . $path . 'header-ribbon-step3.png" alt="Register" /></a>';
      }
    }
  }
  else {
    $output .= '<a href="/user/login" title="Log in"><img src="' . $path . 'header-ribbon-login.png" alt="Log in" /></a>';
    $output .= '<a href="/user/register" title="Create account"><img src="' . $path . 'header-ribbon-createaccount.png" alt="Create account" /></a>';
  }

  $output .= '</div>';

  return $output;
}

/**
 * Implementation of hook_user().
 */
function drupalcampaustin_library_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'load') {
    $account->profile_page = drupalcampaustin_library_user_profile_page($account->uid);
  }
}

function drupalcampaustin_library_user_profile_page($uid) {
  if ($uid != 0) {
    $profile_node = content_profile_load('profile', $uid);
    if ($profile_node != FALSE) {
      return $profile_node->nid;
    }
  }
  return FALSE;
}

/**
 * Check to see if a user has been assigned a certain role.
 *
 * @param $role
 *   The name of the role you're trying to find.
 * @param $user
 *   The user object for the user you're checking; defaults to the current user.
 * @return
 *   TRUE if the user object has the role, FALSE if it does not.
 */
function drupalcampaustin_library_user_has_role($role, $user = NULL) {
  if ($user == NULL) {
    global $user;
  }
  if (is_array($user->roles) && in_array($role, array_values($user->roles))) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implementation of hook_menu().
function drupalcampaustin_library_menu() {
}
 */

/**
 * Implementation of hook_menu_alter().
function drupalcampaustin_library_menu_alter(&$items) {
}
*/

/*
*/
function drupalcampaustin_library_form_alter(&$form, $form_state, $form_id) {
//  print $form_id;

  // Content Profile wants to redirect the form to the user's account page.
  // This has to be done here (instead of hook_form_FORM_ID_alter()) below
  // because Content Profile uses form_alter(), which runs *after* the
  // FORM_ID version.
  if ($form_id == 'profile_node_form') {
    unset($form['#redirect']);
  }
}

function drupalcampaustin_library_form_contact_mail_user_alter(&$form, &$form_state) {
  $profile_page = drupalcampaustin_library_user_profile_page(arg(1));
  if ($profile_page != FALSE) {
    $form['#redirect'] = 'node/' . $profile_page;
  }
  else {
    $form['#redirect'] = '<front>';
  }
}

function drupalcampaustin_library_form_profile_node_form_alter(&$form, &$form_state) {
  // Hide the extraneous title ("Name") field
  $form['title']['#type'] = 'hidden';
  // Add placeholder for #value
  $form['title']['#value'] = NULL;
  // Add a validation function that will fill in the value of the title ("Name") field
  $form['#validate'][] = 'drupalcampaustin_library_profile_node_form_validate';

  $form['revision_information']['#type'] = 'hidden';

//  print_r($form);
}

function drupalcampaustin_library_profile_node_form_validate($form, &$form_state) {
  $name = $form_state['values']['field_profile_firstname'][0]['value'] . ' ' . $form_state['values']['field_profile_lastname'][0]['value'];
  form_set_value($form['title'], $name, $form_state);
}
