<?php
// $Id: uc_views_addresses.module,v 1.1.2.1 2009/10/07 11:43:21 madsph Exp $

/**
 * @file
 * Created with http://drupal.org/project/code_gen
 */

/**
 * Implementation of hook_views_api().
 */
function uc_views_addresses_views_api() {
  return array(
    'api' => '2.0',
    'path' => drupal_get_path('module', 'uc_views_addresses') .'/views',
  );
}

/**
 * Implementation of hook_date_api_fields().
 * on behalf of core fields.
 *
 * All modules that create custom fields that use the
 * 'views_handler_field_date' handler can provide
 * additional information here about the type of
 * date they create so the date can be used by
 * the Date API views date argument and date filter.
 *
 */
function uc_views_addresses_date_api_fields($field) {
  $values = array(
    // The type of date: DATE_UNIX, DATE_ISO, DATE_DATETIME.
    'sql_type' => DATE_UNIX,
    // Timezone handling options: 'none', 'site', 'date', 'utc'.
    'tz_handling' => 'site',
    // Needed only for dates that use 'date' tz_handling.
    'timezone_field' => '',
    // Needed only for dates that use 'date' tz_handling.
    'offset_field' => '',
    // Array of "table.field" values for related fields that should be
    // loaded automatically in the Views SQL.
    'related_fields' => array(),
    // Granularity of this date field's db data.
    'granularity' => array('year', 'month', 'day', 'hour', 'minute', 'second'),
  );
  return $values;
}

?>